#!/usr/bin/env bash

set -e

ACCESS_KEY_ID=$(terraform output example-access-key-id)
SECRET_ACCESS_KEY=$(terraform output example-secret-access-key | base64 --decode | keybase pgp)

cat << EOF > credentials.example
[default]
aws_access_key_id = $ACCESS_KEY_ID
aws_secret_access_key = $SECRET_ACCESS_KEY
EOF

echo "credentials written to credentials.example"

cat << EOF > config.example
[default]
region = us-east-2
output = jsonj
EOF

echo "config written to config.example"